### ISSUE TITLE
Run in browser

### ISSUE THREAD

**Issue by tvb** [ssube/textual-engine#575]
As mentioned [here](https://ssube.github.io/textual-engine/docs/development.html#running) the engine can run in make or docker, how can I run this engine in a browser?

**Comment by ssube** [comment]
You'll need to serve the files somehow. It looks like I have not added the dev server plugin to the esbuild configuration, so you can add that, or use an external server (like http-server or nginx).

To build the browser bundle, start with `make bundle`. That will produce `out/index.html` and `out/browser.mjs`, which are the files you need to serve. Using something like https://www.npmjs.com/package/http-server, that should be `http-server ./out`. 

I often use the server container, and you can mount the files there, so you don't have to restart every time you build them. That looks like `podman run -v ./out:/usr/share/nginx/html:ro docker.io/nginx`.
